# Generated by Django 3.1.4 on 2020-12-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20201206_1514'),
        ('students', '0002_auto_20201206_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroomID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom'),
        ),
    ]
