# Generated by Django 3.1.4 on 2020-12-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20201205_2253'),
        ('students', '0002_auto_20201205_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='students.student')),
            ],
        ),
    ]
