# Generated by Django 3.1.4 on 2020-12-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '__first__'),
        ('classrooms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('teacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='teachers.teacher')),
            ],
        ),
    ]
