# Generated by Django 3.1.4 on 2020-12-05 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0002_teacher_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='school',
            new_name='schoolID',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='subjectID',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='userID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
