# Generated by Django 3.1.4 on 2020-12-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0003_auto_20201205_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='schoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
    ]
