# Generated by Django 3.1.4 on 2020-12-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0004_auto_20201205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
