# Generated by Django 3.1.4 on 2020-12-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_auto_20201205_2253'),
        ('teachers', '0005_auto_20201205_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('teacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teachers.teacher')),
            ],
        ),
    ]
