# Generated by Django 3.1.4 on 2020-12-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20201206_1514'),
        ('teachers', '0006_teacher_classrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Classrooms',
            new_name='Teacher_Classroom',
        ),
    ]
