# Generated by Django 3.1.4 on 2020-12-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('classrooms', '0002_auto_20201205_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects_Classrooms',
            new_name='Subjects_Classroom',
        ),
    ]
