# Generated by Django 3.1.4 on 2020-12-23 00:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='', max_length=25)),
                ('amount', models.IntegerField()),
                ('dueDate', models.DateField(default=datetime.date(2021, 1, 22))),
                ('payDate', models.DateField(null=True)),
                ('token', models.JSONField(default=dict)),
                ('paid', models.BooleanField(default=False)),
                ('schoolID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('studentID', 'semester')},
            },
        ),
    ]
